import {ReactNode} from "react";
import Head from 'next/head'
import styled, {ThemeProvider} from "styled-components";
import {theme} from "../utils/styling";
import GlobalStyles from "../components/atoms/globalStyles";

const Main = styled.div`
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  min-height: 100vh;
`

interface ModuleProps {
    children: ReactNode
}

export default function Layout({children}: ModuleProps) {
    return (
        <ThemeProvider theme={theme}>
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <GlobalStyles/>
                <Main>
                    {children}
                </Main>
            </>
        </ThemeProvider>
    )
}
